# Redis数据库索引（默认为0）  
spring: 
  redis: 
    database: 0
# Redis服务器地址  
    host: 192.168.3.147
# Redis服务器连接端口  
    port: 6379  
# Redis服务器连接密码（默认为空）  
    password:
# 连接池最大连接数（使用负值表示没有限制）  
    pool:
      max-active: 200
# 连接池最大阻塞等待时间（使用负值表示没有限制）  
        max-wait: -1
# 连接池中的最大空闲连接  
        max-idle: 10
# 连接池中的最小空闲连接  
        min-idle: 0
# 连接超时时间（毫秒）  
    timeout: 1000
