server:
  port: 12314
  servlet:
    context-path: /
spring:
  application:
    name: message
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///helloworld?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:12311/eureka
